-- https://webkinzguide.com/wiki/(Item_Guide)_WShop_Food

INSERT INTO food VALUES
(DEFAULT, 1546,  "Almonds", 			 4,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 48, 	 "Apple",				 5,  "Ingredient", "W-Shop", 12, DEFAULT),
(DEFAULT, 1540,  "Apple Juice",			 5,  "Ingredient", "W-Shop", 8,  DEFAULT),
(DEFAULT, 3306,  "Artichoke",			 5,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 59, 	 "Asparagus",			 5,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 1527,  "Bagel", 				 7,  "Ingredient", "W-Shop", 12, DEFAULT),
(DEFAULT, 1535,  "Baked Beans", 		 9,  "Ingredient", "W-Shop", 18, DEFAULT),
(DEFAULT, 1525,  "Baked Potato", 		 7,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 715, 	 "Banana", 				 6,  "Ingredient", "W-Shop", 12, DEFAULT),
(DEFAULT, 1515,  "Blueberries", 		 5,  "Ingredient", "W-Shop", 8,  DEFAULT),
(DEFAULT, 129, 	 "Blueberry Cheesecake", 7,  "Ingredient", "W-Shop", 12, DEFAULT),
(DEFAULT, 717, 	 "Bottled Water", 		 4,  "Ingredient", "W-Shop", 6,  DEFAULT),
(DEFAULT, 711, 	 "Bread", 				 7,  "Ingredient", "W-Shop", 10, DEFAULT),
(DEFAULT, 1524,  "Broccoli", 			 5,  "Ingredient", "W-Shop", 8,  DEFAULT),
(DEFAULT, 1531,  "Burger", 				 12, "Ingredient", "W-Shop", 40, DEFAULT),
(DEFAULT, 122,   "Cake", 				 6,  "Ingredient", "W-Shop", 12, DEFAULT),
(DEFAULT, 17701, "Calico Cat Cookie", 	 15, "Other", 	   "W-Shop", 12, DEFAULT),
(DEFAULT, 120, 	 "Candy Apple", 		 6,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 3308,  "Cantaloupe", 			 8,  "Ingredient", "W-Shop", 20, DEFAULT),
(DEFAULT, 955, 	 "Carrot Cake", 		 25, "Ingredient", "W-Shop", 12, DEFAULT),
(DEFAULT, 78, 	 "Carrots", 			 5,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 86, 	 "Cheeses", 			 7,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 73, 	 "Cherries", 			 6,  "Ingredient", "W-Shop", 8,  DEFAULT),
(DEFAULT, 3338,  "Cherry Pie", 			 10, "Ingredient", "W-Shop", 12, DEFAULT),
(DEFAULT, 716, 	 "Chicken Noodle Soup",  6,  "Ingredient", "W-Shop", 20, DEFAULT),
(DEFAULT, 1532,  "Chicken Nuggets", 	 13, "Ingredient", "W-Shop", 30, DEFAULT),
(DEFAULT, 108, 	 "Chocolate Bar", 		 5,  "Ingredient", "W-Shop", 5,  DEFAULT),
(DEFAULT, 1539,  "Chocolate Milk", 		 6,  "Ingredient", "W-Shop", 15, DEFAULT),
(DEFAULT, 103, 	 "Chocolate Milkshake",  5,  "Ingredient", "W-Shop", 10, DEFAULT),
(DEFAULT, 1548,  "Chocolate Pudding", 	 5,  "Ingredient", "W-Shop", 15, DEFAULT);