-- MySQL Script generated by MySQL Workbench
-- Wed Dec 17 00:18:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kinzcol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kinzcol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kinzcol` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kinzcol` ;

-- -----------------------------------------------------
-- Table `kinzcol`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinzcol`.`account` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kinzcol`.`clothing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinzcol`.`clothing` (
  `clothing_id` INT NOT NULL AUTO_INCREMENT,
  `asset_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `price` INT NULL DEFAULT NULL,
  `type_prim` ENUM('Clothing', 'Recipe Clothing') NOT NULL,
  `theme` VARCHAR(45) NULL DEFAULT NULL,
  `location` ENUM('Kinzstyle Outlet', 'Kinzstyle Shop') NOT NULL,
  `deluxe` TINYINT(1) NOT NULL DEFAULT '0',
  `owned` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`clothing_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kinzcol`.`account_has_clothing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinzcol`.`account_has_clothing` (
  `account_user_id` INT NOT NULL AUTO_INCREMENT,
  `clothing_clothing_id` INT NOT NULL,
  `clothing_owned` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`account_user_id`, `clothing_clothing_id`),
  INDEX `fk_account_has_clothing_clothing1_idx` (`clothing_clothing_id` ASC) VISIBLE,
  INDEX `fk_account_has_clothing_account1_idx` (`account_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_clothing_account1`
    FOREIGN KEY (`account_user_id`)
    REFERENCES `kinzcol`.`account` (`user_id`),
  CONSTRAINT `fk_account_has_clothing_clothing1`
    FOREIGN KEY (`clothing_clothing_id`)
    REFERENCES `kinzcol`.`clothing` (`clothing_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kinzcol`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinzcol`.`food` (
  `food_id` INT NOT NULL AUTO_INCREMENT,
  `asset_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL,
  `type_prim` ENUM('Ingredient', 'Recipe Food', 'Pet-Specific Food', 'Other') NOT NULL,
  `location` ENUM('W-Shop', 'Kinzville Park') NOT NULL,
  `hunger_boost` INT NULL DEFAULT NULL,
  `owned` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`food_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kinzcol`.`account_has_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinzcol`.`account_has_food` (
  `account_user_id` INT NOT NULL AUTO_INCREMENT,
  `food_food_id` INT NOT NULL,
  `food_owned` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`account_user_id`, `food_food_id`),
  INDEX `fk_account_has_food_food1_idx` (`food_food_id` ASC) VISIBLE,
  INDEX `fk_account_has_food_account1_idx` (`account_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_food_account1`
    FOREIGN KEY (`account_user_id`)
    REFERENCES `kinzcol`.`account` (`user_id`),
  CONSTRAINT `fk_account_has_food_food1`
    FOREIGN KEY (`food_food_id`)
    REFERENCES `kinzcol`.`food` (`food_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kinzcol`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinzcol`.`item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `asset_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `item_price` INT NOT NULL,
  `type_prim` ENUM('Furniture', 'Decorations', 'TYPE') NOT NULL DEFAULT 'TYPE',
  `dimensions` VARCHAR(5) NULL DEFAULT NULL,
  `theme` VARCHAR(45) NULL DEFAULT NULL,
  `location` ENUM('W-Shop', 'Curio Shop', 'Other') NOT NULL,
  `deluxe` TINYINT(1) NOT NULL DEFAULT '0',
  `first_available` VARCHAR(7) NULL DEFAULT NULL,
  `owned` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kinzcol`.`account_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kinzcol`.`account_has_item` (
  `account_user_id` INT NOT NULL AUTO_INCREMENT,
  `item_item_id` INT NOT NULL,
  `item_owned` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`account_user_id`, `item_item_id`),
  INDEX `fk_account_has_item_item1_idx` (`item_item_id` ASC) VISIBLE,
  INDEX `fk_account_has_item_account1_idx` (`account_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_item_account1`
    FOREIGN KEY (`account_user_id`)
    REFERENCES `kinzcol`.`account` (`user_id`),
  CONSTRAINT `fk_account_has_item_item1`
    FOREIGN KEY (`item_item_id`)
    REFERENCES `kinzcol`.`item` (`item_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
